name: test_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.5
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

#------------------- PACKAGES-------------------#
  dio: ^5.4.3+1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0


flutter:
  uses-material-design: true

  # ---------------- LOCAL ASSETS ----------------
  # assets:
  #   - assets/logos/